version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ci
      prefix-development: ci

  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: build
      prefix-development: build
