name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      agent--tag_name: ${{ steps.release.outputs.agent--tag_name}}
      agent--release_created: ${{ steps.release.outputs.agent--release_created}}
      server--tag_name: ${{ steps.release.outputs.server--tag_name}}
      server--release_created: ${{ steps.release.outputs.server--release_created}}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo "${{ toJson(steps.release.outputs) }}"


  release-agent:
    if: ${{needs.release-please.outputs.agent--release_created}}
    runs-on: ubuntu-latest
    needs: release-please
    strategy:
      matrix:
        target:
          - linux-x64
          - linux-arm64
          - windows-x64
          - darwin-x64
          - darwin-arm64
          - linux-x64-musl
          - linux-arm64-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: tool-versions
        name: Get Tool Versions
        run: |
          for tool in $(cat .tool-versions | awk '{print $1}'); do
            echo "$tool=$(grep "$tool" .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT
          done
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ steps.tool-versions.outputs.bun }}
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/bun.lock') }}
      - name: Bun Install
        run: bun install --frozen-lockfile
      - name: Build Agent
        working-directory: agent
        run: bun build --compile --target bun-${{ matrix.target }}  --minify --sourcemap --bytecode ./index.ts --outfile devicemonster-agent-${{ matrix.target }}
      - name: Upload Release Artifact
        working-directory: agent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.agent--tag_name }} devicemonster-agent-${{ matrix.target }}

  release-server:
    if: ${{needs.release-please.outputs.server--release_created}}
    runs-on: ubuntu-latest
    needs: release-please
    strategy:
      matrix:
        target:
          - linux-x64
          - linux-arm64
          - windows-x64
          - darwin-x64
          - darwin-arm64
          - linux-x64-musl
          - linux-arm64-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: tool-versions
        name: Get Tool Versions
        run: |
          for tool in $(cat .tool-versions | awk '{print $1}'); do
            echo "$tool=$(grep "$tool" .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT
          done
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ steps.tool-versions.outputs.bun }}
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/bun.lock') }}
      - name: Bun Install
        run: bun install --frozen-lockfile
      # Asset compilation is broken until this is fixed:
      # https://github.com/oven-sh/bun/issues/11895
      - name: Build Server
        working-directory: server
        run: bun build --compile --target bun-${{ matrix.target }}  --minify --sourcemap --bytecode ./src/index.tsx --outfile devicemonster-server-${{ matrix.target }}
      - name: Upload Release Artifact
        working-directory: server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.server--tag_name }} devicemonster-server-${{ matrix.target }}
